// Match the shipped tools, not hypothetical encoder/features or savings claims.
const e = (s) => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const head = (eyebrow,title,copy='') => `<div class="tg-section-head"><div><span class="tg-eyebrow">${e(eyebrow)}</span><h2>${e(title)}</h2></div>${copy?`<p>${e(copy)}</p>`:''}</div>`;
const section = (id,content,classes='') => `<section class="tg-section ${classes}" id="${id}">${content}</section>`;
const cards = (items) => `<div class="tg-card-grid">${items.map(([icon,title,copy])=>`<article class="tg-card"><i data-lucide="${icon}" aria-hidden="true"></i><h3>${e(title)}</h3><p>${copy}</p></article>`).join('')}</div>`;
const table = (caption,headers,rows) => `<div class="tg-table-wrap" role="region" aria-label="${e(caption)}" tabindex="0"><span class="tg-table-hint">Scroll sideways to compare all columns →</span><table><caption>${e(caption)}</caption><thead><tr>${headers.map(x=>`<th scope="col">${e(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>i===0?`<th scope="row">${x}</th>`:`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const faq = (items) => items.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${a}</p></details>`).join('');
const steps = (items) => `<ol class="tg-steps">${items.map(([title,copy],i)=>`<li><span class="tg-step-number">0${i+1}</span><div><h3>${e(title)}</h3><p>${copy}</p></div></li>`).join('')}</ol>`;
const sources = (items) => `<p class="tg-source-note">Technical references: ${items.map(([title,url])=>`<a href="${url}">${e(title)}</a>`).join(' · ')}. Tool-specific behavior follows PMW’s current implementation.</p>`;
const feature = (kind,eyebrow,title,body,art,caption) => `<div class="tg-feature tg-feature-${kind}"><div class="tg-feature-copy"><span class="tg-eyebrow">${e(eyebrow)}</span><h3>${e(title)}</h3>${body}</div><figure class="tg-feature-art">${art}<figcaption>${caption}</figcaption></figure></div>`;
const stories = (items) => `<div class="tg-stories">${items.map(([label,title,copy,route],i)=>`<article><span class="tg-story-number">0${i+1}</span><div><span class="tg-eyebrow">${e(label)}</span><h3>${e(title)}</h3><p>${copy}</p><p class="tg-story-route">${route}</p></div></article>`).join('')}</div>`;
const inspect = (items) => `<div class="tg-inspect-grid">${items.map(([label,title,copy])=>`<article><span>${e(label)}</span><h3>${e(title)}</h3><p>${copy}</p></article>`).join('')}</div>`;
const related = (active) => section('next-step', head('One change at a time','Choose your next step') + `<div class="tg-next-grid">${[
  ['compressor','image-compressor','Compress','Make the file lighter. Check quality and pixel dimensions.'],
  ['resizer','image-resizer','Resize','Change width and height. Keep the composition in proportion.'],
  ['converter','image-converter','Convert','Change the format for the app or device that will use it.']
].filter(x=>x[0]!==active).map(([,slug,title,copy])=>`<a href="../${slug}/"><span class="tg-eyebrow">PMW Tools</span><h3>${title}<i data-lucide="arrow-up-right" aria-hidden="true"></i></h3><p>${copy}</p></a>`).join('')}<a href="../../#screen-fit"><span class="tg-eyebrow">Wallpaper guide</span><h3>Fit your screen<i data-lucide="arrow-up-right" aria-hidden="true"></i></h3><p>Compare portrait and landscape artwork with your display’s shape.</p></a></div>`);

export const toolPages = {
  compressor: {
    slug:'image-compressor',name:'Image Compressor',eyebrow:'A smaller file, an informed choice',
    intro:'Compress JPG, PNG and WebP on your device. Compare the size estimate, then check the exported detail and dimensions before you download.',
    promise:'Keep the detail that matters.',
    badges:['JPG · PNG · WebP','On-device processing','Quality & size guidance'],
    description:'Compress JPG, PNG and WebP images in your browser. Compare quality settings, understand target-size limits and inspect the exported dimensions.',
    graphicAlt:'Illustrated compression workflow: a source image, encoding settings and an export. No fixed saving is promised.',
    jump:[['compression-workflow','How to use it'],['quality-lab','Quality demo'],['compression-formats','Format guide'],['compression-size-budget','Size budget'],['compression-faq','Troubleshooting']],
    guide: () => [
      section('compression-workflow',head('Start with the use, not a percentage','A sensible compression workflow','A lower setting is useful only if the export still works where you intend to use it.')+steps([
        ['Start from your original','Upload a JPG, PNG or WebP. Keep a separate original; repeatedly exporting a lossy image can accumulate visible artifacts.'],
        ['Choose a starting setting','Try 85% for detail you want to inspect carefully or 70% for an everyday copy. The setting is not the percentage of file size you will save.'],
        ['Use a target when you have one','Enter a preferred size in KB if a form or upload has a limit. PMW searches for a smaller export, but the target is best effort.'],
        ['Inspect the result','Check edges, text, gradients and the returned width/height. PMW can reduce dimensions while pursuing its size target. Download only when both detail and size are suitable.']
      ])),
      section('quality-lab',head('A small, real experiment','See what a quality setting changes','Run this browser-generated JPEG example. Its measured size describes this sample, not a promised result for your upload.')+`<div class="tg-lab" data-quality-lab><div class="tg-lab-images"><figure><img src="/thumbnails/google-drive/14iXY0uyDwJ68hXvBYB0KePk80Qno3m1r.webp" width="240" height="427" alt="Alpine creek sample used for the quality demonstration" loading="lazy"><figcaption>Source preview · 240 × 427</figcaption></figure><figure><div class="tg-demo-output"><img id="guideQualityImage" width="240" height="427" alt="JPEG output of the quality demonstration" hidden><span id="guideQualityPlaceholder">Run the example to compare the export.</span></div><figcaption id="guideQualitySize" aria-live="polite">JPEG sample export · waiting</figcaption></figure></div><div class="tg-lab-controls"><span class="tg-eyebrow">JPEG sample only</span><h3>Try a lower setting. Look closely.</h3><label for="guideQuality">Demo quality <output id="guideQualityValue">70%</output></label><input id="guideQuality" type="range" min="10" max="95" value="70"><button class="tg-button" id="guideRunQuality" type="button">Run quality example</button><p>Look at the small leaves, mountain edges and sky. A JPEG export may be larger than the source WebP at some settings. These formats encode the picture differently.</p><p class="tg-small">The demo uses a local browsing preview and keeps its dimensions fixed. The main compressor keeps your input format and may change dimensions.</p></div></div>`,'tg-lab-section'),
      section('compression-settings',head('Four starting points','Choose a preset, then verify it')+`<div class="tg-preset-guide">${[
        [85,'High quality','Start here for small text, fine edges or an image you need to examine closely.'],
        [70,'Balanced','A practical first attempt for everyday sharing. Inspect the output at the size it will be viewed.'],
        [55,'Small size','Try when an upload limit matters. Expect more visible changes or a smaller pixel frame.'],
        [40,'Maximum compression','Use for a disposable sharing copy when size matters more than fine detail. Keep your original.']
      ].map(([value,title,copy])=>`<article><span class="tg-preset-value">${value}<small>%</small></span><h3>${title}</h3><p>${copy}</p><a class="tg-text-link" href="#tool-workspace" data-guide-quality="${value}">Use this setting in the tool</a></article>`).join('')}</div><p class="tg-callout"><strong>Read the returned dimensions.</strong> This compressor searches both encoding settings and smaller pixel sizes. It does not offer a “preserve dimensions” switch or guarantee lossless output.</p>`),
      section('compression-formats',head('The format changes the trade-off','JPG, PNG and WebP behave differently')+table('Compression behavior by input format',['Format','Useful for','What this tool does'],[
        ['JPG','Photographs and textured scenes','Keeps JPG output and tries lower JPEG quality plus smaller dimensions. Transparency is not supported.'],
        ['PNG','Screenshots, sharp text and transparent graphics','Keeps PNG output. Browser PNG encoding ignores the JPEG-style quality parameter; size reduction here can come from reducing dimensions.'],
        ['WebP','Photos or graphics when the receiving app supports WebP','Keeps WebP output and tries quality/dimension changes. Alpha can be retained, but still inspect edges and the exported size.']
      ])+`<p class="tg-prose">A format change is a separate choice. If you want a PNG converted to WebP, use the <a href="../image-converter/">Media Converter</a> or choose an export format in the <a href="../image-resizer/">Resizer</a>. A larger file is not automatically a better image, and a smaller file is not automatically suitable for every use.</p>`+sources([['Canvas export quality','https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob'],['Image format guide','https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Image_types']])),
      section('compression-use-cases',head('Choose the copy you actually need','Practical starting choices')+cards([
        ['image','Website photography','Choose the display dimensions first in <a href="../image-resizer/">Resizer</a>, then inspect a compression export. Avoid sending a huge original for a small on-screen image.'],
        ['type','Screenshots and logos','Prioritize readable text and clean edges. Inspect PNG output dimensions; a smaller pixel frame can make small lettering harder to read. Keep a vector original separately if you have one.'],
        ['mail','Attachments and forms','Use the receiving site’s actual byte limit as the target. Check the downloaded file rather than assuming that the quality percentage is a size guarantee.']
      ])),
      section('compression-size-budget',head('Work backwards from the limit','Build a useful size budget')+feature('budget','Illustrative numbers, not measured savings','An upload limit is a boundary, not a quality setting.',`<p>Imagine a form that accepts a file smaller than 500KB. A 1.8MB original will not fit, but moving the quality slider to 50% does not mean that it will become 900KB—or that it will pass the form’s limit.</p><p>Choose a preferred target with a little room below the limit, such as 450KB. Inspect PMW’s returned size and dimensions. If the result is still too large, make a new attempt from your original, or first use the Resizer to choose fewer pixels when the form allows it.</p><p>A receiving site may count kilobytes differently. PMW’s target field treats 1KB as 1,024 bytes. The receiving site’s validation is the final check; a number that looks close is not a guarantee of acceptance.</p>`,`<div class="tg-budget-art" aria-label="Illustrative size budget: 500KB upload limit, 450KB preferred target, 50KB room below the limit"><div class="tg-art-topline"><span>EXAMPLE UPLOAD BUDGET</span><i data-lucide="gauge" aria-hidden="true"></i></div><strong>500<small>KB limit</small></strong><div class="tg-budget-track"><span>450KB target</span><em>50KB</em></div><div class="tg-art-key"><span><b></b>Preferred target</span><span>Room below the limit</span></div><p>Check the actual exported file.</p></div>`,`Example only. A target is best effort; the final image may still exceed it.`)+`<div class="tg-inline-note"><i data-lucide="save" aria-hidden="true"></i><p><strong>Keep two copies.</strong> Give the sharing copy a descriptive name such as <code>mountain-web.jpg</code> and keep the original separately. That makes it easier to revisit quality choices without repeatedly compressing an already compressed file.</p></div>`),
      section('compression-inspection',head('Look beyond the size number','Four places to inspect your picture','Compare at the intended viewing size first, then zoom in where detail matters. Do not judge a full-size image only from a tiny preview.')+inspect([
        ['A · Fine edges','Small lettering and outlines','Look for halos around text, jagged diagonal lines and soft edges. If a logo or screenshot needs precise detail, a high setting is a starting point—not a substitute for inspecting the exported dimensions.'],
        ['B · Smooth tones','Skies, gradients and shadows','Look for bands in a smooth sky or blocks in dark areas. These can become more noticeable after another app processes your upload. Keep an original so you can choose a different export if needed.'],
        ['C · Texture','Leaves, hair and fabric','Fine texture can turn into a soft patch even while large shapes look unchanged. Decide whether that detail matters to the actual use: a small attachment and a large portfolio image have different needs.'],
        ['D · Pixel frame','Width and height after export','A lighter result may also be smaller in pixels. Confirm that it still has enough resolution for the destination. The compressor can downscale while searching for the target size.']
      ])),
      section('compression-decisions',head('A deliberate second attempt','What to change when the first copy is not right')+stories([
        ['Too heavy','The image looks good, but the file is too big.','Check whether it contains many more pixels than the destination needs. Resize from the original to a suitable proportional frame, then compress that copy. If a PNG photograph remains large, compare a WebP or JPG export in the Converter when the destination accepts it.','Right dimensions → suitable format → inspect compression'],
        ['Too soft','The file fits, but important detail has disappeared.','Start again from the original. Raise the quality setting and check the returned dimensions. If the size requirement is extremely tight, decide which matters more: a smaller display frame or visible artifacts at full size. No percentage can remove that trade-off.','Original → higher setting → compare at viewing size'],
        ['Wrong destination','The export looks fine, but an upload rejects it.','Read the accepted formats, maximum dimensions and byte limit together. A small WebP is not useful to a form that accepts only JPG. Use the Converter for a format requirement and the Resizer for a pixel requirement rather than repeating compression blindly.','Read the requirement → choose the matching tool']
      ])),
      section('compression-faq',head('When the result needs a second look','Compression questions answered')+`<div class="tg-faq">${faq([
        ['Does 70% mean a 30% smaller file?','No. It is a requested quality setting. Format, image detail, the original encoding and the selected pixel scale affect the size. PMW’s PNG path handles quality differently from JPEG/WebP.'],
        ['Can I keep the original width and height?','There is no dimension-lock control in this compressor. Its size search can downscale the image. Inspect the result dimensions; keep the original when a full-resolution file is essential.'],
        ['Why is the target size not reached?','The target is preferred rather than guaranteed. The tool can return a smaller file that is still above the target, or report that an already optimized image could not be made smaller.'],
        ['Will transparent areas remain transparent?','PNG and WebP exports can retain alpha. JPG cannot. This compressor keeps the input format; use the converter if you want a different one.'],
        ['What are the free limits?','The current free allowance is nine compressions per day, one image at a time, with a 10MB per-file limit and large-dimension restrictions. Premium enables batches/higher allowances; device memory still limits large images.'],
        ['Where does the image go?','The compressor reads and encodes the file in your browser rather than uploading its contents to PMW. The page still makes ordinary requests for its libraries and analytics. Save the export before closing the tab.']
      ])}</div>`), related('compressor')
    ].join('\n')
  },
  resizer: {
    slug:'image-resizer',name:'Image Resizer',eyebrow:'Pixels with a purpose',
    intro:'Set the dimensions your next use needs. Keep the original proportions, choose an export format and inspect your resized image on the device that will show it.',
    promise:'Right size. Right proportions.',
    badges:['Exact pixel dimensions','Aspect-ratio control','JPG · PNG · WebP'],
    description:'Resize JPG, PNG and WebP in your browser. Calculate aspect ratios, understand presets and stretching, and choose suitable export dimensions.',
    graphicAlt:'Illustrated proportional resize: a 941 by 1672 portrait becomes a 480 by 853 portrait, keeping approximately the same shape.',
    jump:[['resize-workflow','How to use it'],['ratio-calculator','Ratio calculator'],['resize-presets','Size guide'],['resize-pixel-budget','Pixel example'],['resize-faq','Troubleshooting']],
    guide: () => [
      section('resize-workflow',head('Keep shape and size separate','Resize with a clear destination')+steps([
        ['Read the original dimensions','Upload a JPG, PNG or WebP and check its width and height. Start from the full-size original when you have it.'],
        ['Change one dimension','For a proportional resize, keep aspect ratio enabled and edit width or height manually. PMW calculates the other value from the first uploaded image.'],
        ['Check a preset’s shape','A preset sets both width and height. It does not automatically crop or add padding to suit your source. Different ratios can stretch the image.'],
        ['Choose the export','Keep the original format or choose JPG, PNG or WebP. Download the result, check its dimensions and view it where it will be used.']
      ])),
      section('ratio-calculator',head('Try the calculation','One width. A matching height.','Enter the source dimensions and your desired width. This calculator is an example helper; it does not change your uploaded image.')+`<div class="tg-calculator"><div class="tg-calculator-inputs"><div class="tg-input-pair"><label>Source width<input id="guideSourceWidth" type="number" min="1" max="50000" value="1920"></label><label>Source height<input id="guideSourceHeight" type="number" min="1" max="50000" value="1080"></label></div><label>Target width<input id="guideTargetWidth" type="number" min="1" max="50000" value="1200"></label><p class="tg-small">Height = target width × source height ÷ source width. Round to the nearest whole pixel.</p></div><div class="tg-calculator-result" aria-live="polite"><span class="tg-eyebrow">Matching dimensions</span><output id="guideRatioResult">1200 × 675</output><p id="guideRatioSummary">The 16:9 shape is preserved. Pixel count changes; file size depends on the format and content.</p><div class="tg-ratio-frame"><span id="guideRatioFrame" aria-hidden="true"></span></div></div></div>`),
      section('resize-shape',head('A square is a different shape','Proportional resize versus stretching')+`<div class="tg-shape-demo"><figure><img src="/thumbnails/google-drive/14iXY0uyDwJ68hXvBYB0KePk80Qno3m1r.webp" width="240" height="427" alt="Portrait alpine artwork in its original proportions" loading="lazy"><figcaption><strong>Keep the proportions</strong><span>The peaks and the creek retain their shapes.</span></figcaption></figure><figure><img class="tg-stretched" src="/thumbnails/google-drive/14iXY0uyDwJ68hXvBYB0KePk80Qno3m1r.webp" width="240" height="240" alt="The same portrait stretched into a square, with widened mountains" loading="lazy"><figcaption><strong>Unlock and change the ratio</strong><span>Setting a portrait to a square stretches the scene here.</span></figcaption></figure><div><h3>A resize is not an automatic crop.</h3><p>PMW draws the whole image into the requested dimensions. A crop removes part of the image; padding adds space around it. This resizer does not provide those separate modes.</p><p>For a different screen shape, prepare a crop in an image editor first, or choose <a href="../../#screen-fit">wallpaper artwork with a matching orientation</a>.</p></div></div>`),
      section('resize-presets',head('A few useful frame shapes','Understand the preset before selecting it')+table('Preset shape and intended use',['Preset','Shape','Useful starting point'],[
        ['1920 × 1080','16:9 landscape','A full-HD display or a wide image layout; check your actual display resolution.'],
        ['1366 × 768','Approximately 16:9','A matching laptop screen or a smaller wide copy.'],
        ['1280 × 720','16:9 landscape','A smaller wide image where full-HD detail is unnecessary.'],
        ['1080 × 1920','9:16 portrait','A portrait layout. Taller phones may still crop it when set to fill.'],
        ['1080 × 1080','1:1 square','A square image slot. A nonsquare source will need a prepared crop or will be distorted.'],
        ['3840 × 2160','16:9 landscape','A 4K-sized pixel frame; a smaller source does not gain real detail from upscaling.']
      ])+`<p class="tg-callout"><strong>Presets set exact dimensions.</strong> The aspect-ratio lock updates the other field during manual entry. Always compare both numbers after clicking a preset.</p>`),
      section('resize-export',head('Size is only one part of the export','Keep detail, format and transparency in view')+cards([
        ['scan','Avoid unnecessary upscaling','If your source is 941 × 1672, creating 1080 × 1920 interpolates pixels. It changes the file dimensions but does not reveal detail that was absent in the source.'],
        ['layers','Choose an appropriate format','PNG preserves transparency and sharp graphic edges. JPG uses a white background for transparent areas in this tool. WebP can retain alpha when supported. The PNG quality slider is hidden because it does not work like JPEG quality.'],
        ['printer','Think in pixels for print','An 1800 × 1200 image printed at 300 pixels per inch is 6 × 4 inches. This page changes pixels, not a print-DPI setting; your print software decides the physical size and quality.']
      ])),
      section('resize-pixel-budget',head('Width × height tells a useful story','Half the width is a quarter of the pixels')+feature('pixels','A worked 16:9 example','960 × 540 is not half of 1920 × 1080 in pixel count.',`<p>A 1920 × 1080 image contains 2,073,600 pixels. Reduce both dimensions by half and the 960 × 540 copy contains 518,400 pixels: one quarter of the source pixel count, with the same 16:9 proportions.</p><p>This explains why choosing appropriate dimensions can help with web delivery. It does not predict a 75% reduction in file size. The format, encoding settings and the detail inside the picture determine how many bytes those pixels need.</p><p>For a 480-pixel-wide display slot, you might prepare a 960-pixel-wide copy for a two-times pixel-density screen when your source is large enough. The layout and device decide whether those extra pixels are useful. Avoid making every small preview as large as the original.</p>`,`<div class="tg-pixel-art" aria-label="Proportional pixel example: 1920 by 1080 has four times as many pixels as 960 by 540"><div class="tg-art-topline"><span>SAME SHAPE · DIFFERENT PIXEL COUNT</span></div><div class="tg-pixel-frame"><span>1920 × 1080</span><div><span>960 × 540</span><small>¼ of the pixels</small></div></div><div class="tg-art-key"><span>2,073,600 source pixels</span><span>518,400 target pixels</span></div></div>`,`The smaller frame is half the width and half the height. It is not a file-size forecast.`)+table('Worked proportional landscape sizes',['Width × height','Pixel count','Share of the original pixels'],[
        ['1920 × 1080','2,073,600','100% — source example'],['1280 × 720','921,600','About 44.4%'],['960 × 540','518,400','25%'],['480 × 270','129,600','6.25%']
      ])),
      section('resize-destinations',head('The destination sets the dimensions','Three ways to plan a resize')+stories([
        ['For the web','Start with the displayed slot.','Find the approximate width the image will occupy, then consider whether a higher-density version is useful. Keep its original ratio unless the layout specifically requires a crop. Review the file size after export; a large PNG and a JPG of the same dimensions can have very different byte sizes.','Display slot → proportional dimensions → inspect file size'],
        ['For a wallpaper','Match the artwork’s shape to the screen.','A phone and a desktop usually need different orientations. Resizing a portrait into landscape does not add scenery to the sides; it stretches the source in this tool. Choose suitable artwork or prepare a crop elsewhere. Your device’s fill/fit setting can still change how the picture appears.','Screen orientation → matching artwork → suitable pixel frame'],
        ['For a print','Calculate from physical size, then check the source.','A 6 × 4 inch print at 300 pixels per inch requires 1800 × 1200 pixels. This is an arithmetic example, not a universal print requirement. Ask the printer what it needs. If the source is smaller, increasing the numbers cannot restore missing detail.','Print size × requested pixels per inch → required pixels']
      ])),
      section('resize-inspection',head('Before the final download','Check the four parts of a good resize')+inspect([
        ['01 · Shape','Does the subject still look natural?','Check faces, circles and familiar objects. If they look wider or taller, compare the source and target ratios. Re-enable the aspect lock and enter one dimension manually.'],
        ['02 · Detail','Are you enlarging or reducing?','Small text can disappear when you reduce the frame. Enlarging can soften edges without adding information. View the export at its intended size rather than relying only on a zoomed-out thumbnail.'],
        ['03 · Background','Is transparency still appropriate?','JPG output fills transparent areas with white here. Choose PNG or supported WebP if an overlay needs transparency. Check the edge against the background where the image will actually be placed.'],
        ['04 · Delivery','Does the destination accept the copy?','Confirm the requested dimensions, accepted format and file-size limit. Keep the original and use a descriptive export filename so you can distinguish the resized version later.']
      ])),
      section('resize-faq',head('Before you export','Resizing questions answered')+`<div class="tg-faq">${faq([
        ['Why does the image look stretched?','The target ratio differs from the original. Enable keep aspect ratio and edit one dimension manually, or prepare a crop before uploading. A preset is not an automatic crop.'],
        ['Will resizing to 4K make it sharper?','It creates a 4K-sized file, not new source detail. Upscaling estimates new pixels from existing ones. A suitable original is the better starting point.'],
        ['Does resizing guarantee a smaller file?','No. Pixel count, output format, encoding settings and content all matter. Use the <a href="../image-compressor/">Compressor</a> when a byte limit is your main constraint.'],
        ['What can I resize on the free plan?','The current allowance is 13 resizes per day, one image at a time, up to 10MB per input. Free output limits are width up to 3840, height up to 2160 and up to 8,294,400 pixels. Both dimensions matter, including for tall portraits.'],
        ['How do batches handle aspect ratio?','The width and height are shared across the batch, and the manual aspect calculation uses the first image. Review mixed-orientation batches carefully rather than assuming every image will keep its own ratio.'],
        ['Are my files uploaded or kept?','Resizing and export happen locally in the browser. PMW does not receive the file contents through this tool. Ordinary page/library/analytics requests still occur. Save the result before closing the page.']
      ])}</div>`+sources([['Canvas export types and quality','https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob']])),related('resizer')
    ].join('\n')
  },
  converter: {
    slug:'image-converter',name:'Media Converter',eyebrow:'Images, motion and sound',
    intro:'Choose the format your next app or device can use. Convert images, video and audio on your device, with clear choices for quality, sound and compatibility.',
    promise:'The format your next step needs.',
    badges:['Image · Video · Audio','Multiple-file queue','On-device conversion'],
    description:'Convert image, video and audio files in your browser. Compare formats and codecs, understand quality and animation limits, and troubleshoot exports.',
    graphicAlt:'Illustrated conversion examples: JPG to WebP, MOV to MP4 and WAV to MP3, processed locally.',
    jump:[['convert-workflow','How to use it'],['format-picker','Format finder'],['media-formats','Format guide'],['container-codec-guide','Containers & codecs'],['convert-faq','Troubleshooting']],
    guide: () => [
      section('convert-workflow',head('Choose the destination first','A file extension is not the whole story')+steps([
        ['Select the media family','Use Image for a still picture, Video for a moving clip, or Audio for a sound file. GIF animation belongs in Video mode; Image mode exports a single frame.'],
        ['Choose the receiving app’s format','Check what the destination accepts. A video container such as MP4 also holds particular codecs, so a matching extension alone does not guarantee playback.'],
        ['Review available controls','Quality means different things for images, video and audio. Video can retain or omit sound; GIF has no audio. Explicit image/audio metadata stripping is a Premium option.'],
        ['Convert and test the result','Save the export and open it in the actual destination. Keep the source: re-encoding cannot restore lost detail or sound information.']
      ])),
      section('format-picker',head('Start with what you need','Find a useful output','This guide suggests a starting format. The target app’s requirements take precedence.')+`<div class="tg-format-finder"><div><label for="guideMediaFamily">Media family</label><select id="guideMediaFamily"><option value="image">Image</option><option value="video">Video</option><option value="audio">Audio</option></select><label for="guideFormatGoal">Main requirement</label><select id="guideFormatGoal"><option value="share">Everyday sharing</option><option value="transparent">Transparent graphic</option><option value="web">Web delivery</option></select></div><div class="tg-format-answer" aria-live="polite"><span class="tg-eyebrow">A starting format</span><output id="guideFormatAnswer">JPG</output><p id="guideFormatReason">Useful for photographic sharing when transparency is unnecessary. Check the receiving app’s supported formats.</p><a id="guideApplyFormat" class="tg-button" href="#tool-workspace">Select this format in the converter</a><p class="tg-small">Selecting a format does not start conversion or upload a file.</p></div></div>`),
      section('media-formats',head('What the current converter exports','Formats, with a reason to choose them')+`<div class="tg-format-family"><div class="tg-family-title"><i data-lucide="image" aria-hidden="true"></i><div><h3>Still images</h3><p>Image mode produces one frame. PNG and WebP can carry transparency; JPG output uses white behind alpha.</p></div></div>${table('Image output guide',['Output','Useful starting use','What to check'],[
        ['JPG','Photographs for everyday sharing','Lossy encoding; no transparency.'],['PNG','Screenshots, text and transparent graphics','Lossless pixel encoding can mean a larger file.'],['WebP','Web images where supported','Can combine compression and alpha; check the destination app.'],['GIF','A palette-based still image in Image mode','Limited colors; Image mode does not preserve animation.'],['BMP','Simple bitmap compatibility','Often larger; check whether the destination actually needs it.'],['TIFF','An app that requests a TIFF raster','A single raster export, not a promise to preserve layers/pages or professional color data.']
      ])}</div><div class="tg-format-family"><div class="tg-family-title"><i data-lucide="film" aria-hidden="true"></i><div><h3>Video and animation</h3><p>A container holds encoded tracks. The codec combinations below describe this converter’s current output choices.</p></div></div>${table('Video output guide',['Output','Current encoding','Useful starting use'],[
        ['MP4','H.264 + AAC; fast-start layout','Broad playback and sharing. Still test the target player.'],['WebM','VP8 + Opus','Web delivery when that combination is accepted.'],['MOV','H.264 + AAC','A workflow that asks for MOV; this does not create a ProRes master.'],['AVI','MPEG-4 video + MP3','An older workflow that explicitly accepts this combination.'],['MKV','H.264 + AAC','Playback software that supports Matroska; browser playback varies.'],['GIF','Palette animation, no sound','Short loops. Higher settings use more frames, colors and a larger pixel width.']
      ])}</div><div class="tg-format-family"><div class="tg-family-title"><i data-lucide="audio-lines" aria-hidden="true"></i><div><h3>Audio</h3><p>Quality for MP3/AAC/OGG/M4A selects a bitrate tier. WAV and FLAC follow different encoding paths.</p></div></div>${table('Audio output guide',['Output','Current encoding','Useful starting use'],[
        ['MP3','MP3, 128/192/256 kbps tiers','Everyday listening and sharing.'],['WAV','16-bit PCM','An editing workflow that requests uncompressed PCM.'],['AAC','AAC, 128/192/256 kbps tiers','Compact audio in an app that accepts .aac.'],['FLAC','Lossless FLAC encoding','Retain the decoded signal; lost MP3 information is not recovered.'],['OGG','Vorbis, 128/192/256 kbps tiers','An app or player supporting Ogg Vorbis.'],['M4A','AAC in an MP4 audio container','Audio-only playback where M4A is accepted.']
      ])}</div>`+sources([['Containers and codecs','https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Containers'],['Canvas image exports','https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob']])),
      section('conversion-quality',head('Three media families, three trade-offs','Conversion cannot invent source quality')+cards([
        ['image','Image quality','JPEG and WebP settings affect lossy encoding. PNG does not use that quality scale. A transparency-to-JPG conversion uses a white background in PMW.'],
        ['film','Video quality','The slider changes encoding choices; it is not a file-size percentage. GIF output uses 8/12/18 fps and 480/720/1080px width tiers, so converting a video to GIF changes more than its extension.'],
        ['audio-lines','Audio quality','Higher bitrate can produce a larger lossy file. Converting an MP3 to WAV or FLAC does not recreate sounds the MP3 already discarded. Keep a high-quality source for later editing.']
      ])),
      section('conversion-checklist',head('Open the export where it matters','A short checklist before you send it')+`<div class="tg-checklist"><article><span>01</span><h3>Look or listen</h3><p>Check the complete export, not only its filename. For video, verify motion and sound; for images, inspect edges and transparency.</p></article><article><span>02</span><h3>Confirm compatibility</h3><p>Test the target player or upload form. A valid output can still use a codec or format that the destination does not accept.</p></article><article><span>03</span><h3>Keep the source</h3><p>Save your original separately. Avoid repeated lossy conversions, and check metadata if it is important to your workflow.</p></article></div>`),
      section('container-codec-guide',head('Two choices behind a video file','The container is the box. The codecs are what is inside.')+feature('tracks','Understanding the export','An MP4 filename does not tell the whole story.',`<p>A video container packages tracks together, while codecs describe how the picture and sound are encoded. In PMW’s MP4 export, the picture uses H.264 and the audio uses AAC when sound is included. The container is MP4; H.264 and AAC are not alternative file extensions for the same thing.</p><p>That distinction matters when an upload form says “MP4” but also specifies a supported video codec. Two files ending in .mp4 can contain different encodings, so renaming a file does not fix a compatibility problem.</p><p>The format table above lists this tool’s current output combinations. Pick the one your destination accepts, then open the completed export there. A MOV export here also uses H.264 and AAC; choosing MOV does not turn it into a ProRes editing master.</p>`,`<div class="tg-container-art" aria-label="PMW MP4 output contains an H.264 picture track and an AAC sound track when audio is kept"><div class="tg-art-topline"><span>PMW MP4 EXPORT</span><i data-lucide="file-video" aria-hidden="true"></i></div><div class="tg-track"><i data-lucide="film" aria-hidden="true"></i><div><strong>H.264</strong><span>Picture track</span></div><div class="tg-frame-strip" aria-hidden="true"><b></b><b></b><b></b><b></b></div></div><div class="tg-track"><i data-lucide="audio-lines" aria-hidden="true"></i><div><strong>AAC</strong><span>Sound track, when included</span></div><div class="tg-wave" aria-hidden="true">${[14,24,38,20,48,30,18,42,26,12].map(h=>`<b style="height:${h}px"></b>`).join('')}</div></div><p>The MP4 container holds the tracks together.</p></div>`,`Conceptual track diagram, not a preview or analysis of an uploaded file.`)),
      section('conversion-scenarios',head('Make the format serve the next step','Three practical conversion routes')+stories([
        ['Image workflow','A transparent graphic for a web layout.','Use Image mode and choose PNG or WebP when the receiving app supports alpha. A JPG output cannot keep transparency and uses a white background here. Inspect the edge on the intended page background. If you need specific dimensions, prepare a resized copy before choosing the final format.','Check transparency → choose PNG/WebP → inspect edges'],
        ['Video workflow','A short clip for a player or a looping animation.','MP4 is a useful starting choice when the player accepts H.264/AAC. Keep audio enabled if sound matters. For a GIF loop, expect no sound and a reduced frame rate or width depending on the quality tier. Choose Video mode for moving GIF input; Image mode exports a still frame.','Check the player → choose MP4 or GIF → inspect motion and sound'],
        ['Audio workflow','An editing copy or a smaller listening copy.','Choose WAV when the editor requests 16-bit PCM, or MP3/M4A when a compatible player needs a compact listening file. Re-encoding a lossy recording cannot recover discarded sound. Archive a suitable original, and listen to the completed copy before deleting or sharing anything.','Check the editor/player → choose WAV or a lossy format → listen']
      ])),
      section('conversion-expectations',head('What an extension cannot promise','Four conversion misconceptions')+inspect([
        ['01 · Re-encoding','A new extension is not a quality upgrade.','An MP3 exported to FLAC remains limited by the MP3 source. A small image exported to TIFF does not gain new detail. Choose the output for compatibility, not because its name sounds more professional.'],
        ['02 · Size','A converted file can be larger.','Uncompressed audio, palette animation and lossless image encoding can produce more bytes than the input. The quality slider is not a target-size control. Keep the result only when its format and size suit the destination.'],
        ['03 · Structure','Raster export is not a project archive.','Image outputs do not promise to preserve layers, multiple pages, every color profile or editing instructions. Keep an original project file in the app that created it when those properties matter.'],
        ['04 · Device','On-device processing still needs resources.','Large media can use significant memory and take time, particularly on a phone. Leave the tab open and allow the engine to load. A smaller representative copy is useful when a full-length file exceeds practical device limits.']
      ])),
      section('convert-faq',head('Formats are a choice, not a guarantee','Conversion questions answered')+`<div class="tg-faq">${faq([
        ['Can I just rename the extension?','Renaming changes the label, not the encoded contents. A real conversion decodes and exports to another supported format.'],
        ['Why does my GIF stop moving?','Image mode exports one frame. Use Video mode with a GIF input to retain a moving sequence, and remember that GIF output has no sound.'],
        ['Why is the first conversion slower?','Advanced formats and audio/video load the on-device media engine on first use. Processing then depends on the clip, settings and your device. Keep the tab open until the result is ready.'],
        ['Can it convert every file with these extensions?','No. The input must be readable by the browser or bundled media engine. Unusual codecs, corrupt files, protected media and unlisted formats can fail even if the name looks familiar.'],
        ['Will metadata be preserved?','Re-encoding can change or omit metadata even when explicit stripping is off. Image/audio stripping is a Premium control; inspect the exported file if metadata matters. It is not a guarantee to preserve every tag, layer or color profile.'],
        ['What are the file and daily limits?','The current per-file limits are 100MB for images and 200MB for video/audio. Free access includes 13 successful file conversions per day; each file in a queue counts separately. Available device memory can impose lower practical limits.'],
        ['Does my media leave the device?','File processing runs locally in the browser, including the media engine. The page fetches its code and can make normal analytics requests, but this conversion path does not upload your file contents to PMW. Download the result before closing the tab.']
      ])}</div>`),related('converter')
    ].join('\n')
  }
};

export const renderGuide = (type) => {
  const config=toolPages[type];
  return `<div class="tg-guide" id="tool-guide"><nav class="tg-guide-nav" aria-label="Guide contents"><span>In this guide</span>${config.jump.map(([id,label])=>`<a href="#${id}">${e(label)}</a>`).join('')}</nav>${config.guide()}</div>`;
};

export const renderHub = () => `<div class="tg-guide tools-shell tg-hub-guide">${section('choose-a-tool',head('Start with the change you need','Convert, resize or compress?')+`<div class="tg-hub-choices"><a href="image-converter/#media-formats"><i data-lucide="repeat-2" aria-hidden="true"></i><div><h3>Change the format</h3><p>Use the Converter when an app needs a different image, video or audio format. Compare the guide’s output choices before exporting.</p><span class="tg-text-link">Explore formats →</span></div></a><a href="image-resizer/#resize-presets"><i data-lucide="scan" aria-hidden="true"></i><div><h3>Change the dimensions</h3><p>Use the Resizer for a new width and height. Keep proportions during manual entry; a square preset does not automatically crop a portrait.</p><span class="tg-text-link">Explore image sizes →</span></div></a><a href="image-compressor/#compression-settings"><i data-lucide="archive" aria-hidden="true"></i><div><h3>Change the file size</h3><p>Use the Compressor when bytes matter. Inspect the returned detail and dimensions because pursuing a size target can reduce the pixel frame.</p><span class="tg-text-link">Explore quality choices →</span></div></a></div>`)}${section('tools-starting-point',`<div class="tg-hub-note"><i data-lucide="route" aria-hidden="true"></i><div><span class="tg-eyebrow">A simple image workflow</span><h2>Keep an original. Make a useful copy.</h2><p>Choose suitable dimensions, select a format the destination accepts, then compress if you still need fewer bytes. Check the completed export where it will be used. Each tool includes its own guide, examples and current limits; you can read those before choosing a file.</p><p class="tg-small">File contents are processed on your device. Ordinary page, library and analytics requests still occur. Save your export before closing the tab.</p></div></div>`)}</div>`;
